# ----------------------------------------------------------------------------------#
#                                                                                   #
#   Copyright   (C) 2009 - 2024 Coozila! MIT License                                #
#   Coozila! Team    lab@coozila.com                                                #
#                                                                                   #
# ----------------------------------------------------------------------------------#

#   STACK NETWORK    ---------------------------------------------------------------#

networks:

    #   External Private network for all stack services    --------------------------#

    stack_private_network:
        #
        #   SSH command to create the Docker network: docker network create --driver bridge stack_private_network --subnet=172.16.0.0/16
        #
        driver: bridge
        external: true

    # -------------------------------------------------------------------------------#

    #   Internal Private network for memcached services    --------------------------#

    memcached_private_network:
        #
        #   Setup Network Driver in .env or use default bridge
        #
        driver: ${MEMCACHED_PRIVATE_DRIVER:-bridge}
        external: false

    # -------------------------------------------------------------------------------#

    #   Internal Private network for mcrouter services    ---------------------------#

    mcrouter_private_network:
        #
        #   Setup Network Driver in .env or use default bridge
        #
        driver: ${MCROUTER_PRIVATE_DRIVER:-bridge}
        external: false

# ----------------------------------------------------------------------------------#

#   STACK SERVICES    --------------------------------------------------------------#

services:

    #   MEMCACHED SERVER 1    ------------------------------------------------------#

    memcached1:
        image: memcached:${MEMCACHED_SERVER_VERSION:-latest}
        restart: always
        ulimits:
            #
            #   Set memory lock limits
            #
            memlock: ${MEMCACHED_MEMLOCK:-1}
        ports:
            #
            #   Port mapping for Memcached
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11212:11211"
        volumes:
            #
            #   Local time
            #
            - /etc/localtime:/etc/localtime:ro
        networks:
            #
            #   Connect to the private network
            #
            memcached_private_network:
        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

    # ------------------------------------------------------------------------------#

    #   MEMCACHED SERVER 2    ------------------------------------------------------#

    memcached2:
        image: memcached:${MEMCACHED_SERVER_VERSION:-latest}
        restart: always
        ulimits:
            #
            #   Set memory lock limits
            #
            memlock: ${MEMCACHED_MEMLOCK:-1}
        ports:
            #
            #   Port mapping for Memcached
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11213:11211"
        volumes:
            #
            #   Local time
            #
            - /etc/localtime:/etc/localtime:ro
        networks:
            #
            #   Connect to the private network
            #
            memcached_private_network:
        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

    # ------------------------------------------------------------------------------#

    #   MEMCACHED SERVER 3    ------------------------------------------------------#

    memcached3:
        image: memcached:${MEMCACHED_SERVER_VERSION:-latest}
        restart: always
        ulimits:
            #
            #   Set memory lock limits
            #
            memlock: ${MEMCACHED_MEMLOCK:-1}
        ports:
            #
            #   Port mapping for Memcached
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11214:11211"
        volumes:
            #
            #   Local time
            #
            - /etc/localtime:/etc/localtime:ro
        networks:
            #
            #   Connect to the private network
            #
            memcached_private_network:
        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

    # ------------------------------------------------------------------------------#

    #   MEMCACHED SERVER 4    ------------------------------------------------------#

    memcached4:
        image: memcached:${MEMCACHED_SERVER_VERSION:-latest}
        restart: always
        ulimits:
            #
            #   Set memory lock limits
            #
            memlock: ${MEMCACHED_MEMLOCK:-1}
        ports:
            #
            #   Port mapping for Memcached
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11215:11211"
        volumes:
            #
            #   Local time
            #
            - /etc/localtime:/etc/localtime:ro
        networks:
            #
            #   Connect to the private network
            #
            memcached_private_network:
        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

    # ------------------------------------------------------------------------------#

    #   MEMCACHED SERVER 5    ------------------------------------------------------#

    memcached5:
        image: memcached:${MEMCACHED_SERVER_VERSION:-latest}
        restart: always
        ulimits:
            #
            #   Set memory lock limits
            #
            memlock: ${MEMCACHED_MEMLOCK:-1}
        ports:
            #
            #   Port mapping for Memcached
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11216:11211"
        volumes:
            #
            #   Local time
            #
            - /etc/localtime:/etc/localtime:ro
        networks:
            #
            #   Connect to the private network
            #
            memcached_private_network:
        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

    # ------------------------------------------------------------------------------#

    #   MCROUTER 1    ---------------------------------------------------------------#

    mcrouter1:
        image: coozila/mcrouter:${MCROUTER_VERSION:-40.0.0}
        container_name: mcrouter1-${MCROUTER_VERSION:-40.0.0}
        platform: linux/amd64
        hostname: ${MCROUTER_HOSTNAME:-localhost}
        restart: always
        links:
            #
            #   Links to Memcached instances
            #
            - memcached1:memcached1
            - memcached2:memcached2
            - memcached3:memcached3
            - memcached4:memcached4
            - memcached5:memcached5
        command: mcrouter --config-file=/etc/mcrouter/mcrouter_config.json -p 11211
        ports:
            #
            #   Port mapping for Mcrouter
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11211:11211"

        volumes:
            #
            #   Local time
            #

            - /etc/localtime:/etc/localtime:ro

            #
            #   Map config file
            #

            #- ./config/intermediate_mcrouter_config.json:/etc/mcrouter/mcrouter_config.json

            #
            #   Map config file
            #
            - ./config/intermediate_mcrouter_failover_config.json:/etc/mcrouter/mcrouter_config.json

        networks:
            #
            #   Connect to public and private networks
            #
            - stack_private_network
            - memcached_private_network
            - mcrouter_private_network

        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"

    #   MCROUTER 2    ---------------------------------------------------------------#

    mcrouter2:
        image: coozila/mcrouter:${MCROUTER_VERSION:-40.0.0}
        container_name: mcrouter2-${MCROUTER_VERSION:-40.0.0}
        platform: linux/amd64
        hostname: ${MCROUTER_HOSTNAME:-localhost}
        restart: always
        links:
            #
            #   Links to Memcached instances
            #
            - memcached1:memcached1
            - memcached2:memcached2
            - memcached3:memcached3
            - memcached4:memcached4
            - memcached5:memcached5
        command: mcrouter --config-file=/etc/mcrouter/mcrouter_config.json -p 11211
        ports:
            #
            #   Port mapping for Mcrouter
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11221:11211"

        volumes:
            #
            #   Local time
            #
            - /etc/localtime:/etc/localtime:ro
            #
            #   Map config file
            #

            #- ./config/intermediate_mcrouter_config.json:/etc/mcrouter/mcrouter_config.json

            #
            #   Map config file
            #
            - ./config/intermediate_mcrouter_failover_config.json:/etc/mcrouter/mcrouter_config.json

        networks:
            #
            #   Connect to public and private networks
            #
            - stack_private_network
            - memcached_private_network
            - mcrouter_private_network

        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"

    #   MCROUTER 3    ---------------------------------------------------------------#

    mcrouter3:
        image: coozila/mcrouter:${MCROUTER_VERSION:-40.0.0}
        container_name: mcrouter3-${MCROUTER_VERSION:-40.0.0}
        platform: linux/amd64
        hostname: ${MCROUTER_HOSTNAME:-localhost}
        restart: always
        links:
            #
            #   Links to Memcached instances
            #
            - memcached1:memcached1
            - memcached2:memcached2
            - memcached3:memcached3
            - memcached4:memcached4
            - memcached5:memcached5
        command: mcrouter --config-file=/etc/mcrouter/mcrouter_config.json -p 11211
        ports:
            #
            #   Port mapping for Mcrouter
            #
            - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11222:11211"

        volumes:
            #
            #   Local time
            #
            - /etc/localtime:/etc/localtime:ro
            #
            #   Map config file
            #

            #- ./config/intermediate_mcrouter_config.json:/etc/mcrouter/mcrouter_config.json

            #
            #   Map config file
            #
            - ./config/intermediate_mcrouter_failover_config.json:/etc/mcrouter/mcrouter_config.json

        networks:
            #
            #   Connect to public and private networks
            #
            - stack_private_network
            - memcached_private_network
            - mcrouter_private_network

        extra_hosts:
            #
            #   Add extra host entries for internal resolution
            #
            - "host.docker.internal:host-gateway"

# ----------------------------------------------------------------------------------#
